name: Set status

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest
      artifacts-path:
        required: false
        type: string
        default: ''

jobs:
  set-status:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: '${{ inputs.status }}',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}${{inputs.artifacts-path}}`
            });
      - name: Exit with error
        if: ${{ inputs.status == 'failure' }}
        run: exit 1