name: Test Functional

on:
  workflow_call:
    inputs:
      gulp-script:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest
      display:
        required: false
        type: string
        default: ''
env:
  NO_CACHE: ${{ secrets.NO_CACHE }}

jobs:
  test:
    runs-on: inputs.os
    continue-on-error: true
    strategy:
      matrix:
        test-group: [1, 2, 3]
    environment: test-functional
    env:
      RETRY_FAILED_TESTS: true
      TEST_GROUPS_COUNT: 3
      TEST_GROUP_NUMBER: ${{ matrix.test-group }}
      DISPLAY: ${{ inputs.display }}
    steps:
      - run: echo "NO_CACHE is ${{ env.NO_CACHE }}"
      - run: sudo safaridriver --enable
        if: ${{ contains(inputs.os, macos) }}
      - uses: actions/github-script@v3
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'pending',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
      - run: |
          sudo apt install fluxbox
          Xvfb ${{ inputs.display }} -screen 0 1920x1080x24 &
          sleep 3
          fluxbox >/dev/null 2>&1 &
        if: ${{ inputs.display }}
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.merged_sha || github.event.inputs.sha}}

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/github-script@v3
        with:
          script: |
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

            let artifacts = {};

            for(let i = 0;i<36&&!artifacts.total_count;i++,await delay(5000)) {
              try {
                ({ data: artifacts } = await github.actions.listWorkflowRunArtifacts({
                repo: context.repo.repo,
                owner: context.repo.owner,
                run_id: context.payload.inputs.deploy_run_id
              }));
              }
              catch (e) {
                console.log(e);
              }
            }

            const { data: artifact } = await github.request(artifacts.artifacts.find(artifact=> artifact.name === 'npm').archive_download_url);
            require('fs').writeFileSync(require('path').join(process.env.GITHUB_WORKSPACE, 'package.zip'), Buffer.from(artifact))

      - run: |
          unzip package.zip
          tar --strip-components=1 -xzf testcafe-*.tgz

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        if: ${{ !env.NO_CACHE }}
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npx gulp ${{ inputs.gulp-script }}
        timeout-minutes: 60
      - uses: actions/github-script@v3
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'success',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
      - uses: actions/github-script@v3
        if: failure() || cancelled()
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'failure',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
