name: Test Server

on:
  workflow_call:
    inputs:
      test-script:
        required: true
        type: string
      node-version:
        required: false
        type: number
        default: 16
      is-docker:
        required: false
        type: boolean
        default: false    
env:
  NO_CACHE: ${{ secrets.NO_CACHE }}
jobs:  
  test:
    runs-on: ubuntu-latest
    environment: test-server
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'pending',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
            
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.merged_sha || github.event.inputs.sha}}
          
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - uses: actions/github-script@v6
        with:
          script: |
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
            
            let artifacts = {};
            
            for(let i = 0;i<36&&!artifacts.total_count;i++,await delay(5000)) {
              try {
                ({ data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
                repo: context.repo.repo,
                owner: context.repo.owner,
                run_id: context.payload.inputs.deploy_run_id
              }));
              }
              catch (e) {
                console.log(e);
              }
            }

            const artifactName = ${{ inputs.is-docker }} ? 'docker' : 'npm';
            const packageName  = ${{ inputs.is-docker }} ? 'docker.zip' : 'package.zip';

            const { data: artifact } = await github.request(artifacts.artifacts.find(artifact=> artifact.name === artifactName).archive_download_url);
            require('fs').writeFileSync(require('path').join(process.env.GITHUB_WORKSPACE, packageName), Buffer.from(artifact))
        
      - run: |
          unzip package.zip
          tar --strip-components=1 -xzf testcafe-*.tgz
        if: ${{ !inputs.is-docker }}

      - run: |
          unzip docker.zip
          docker load -i testcafe-*.tar
        if: ${{ inputs.is-docker }}
          
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        if: ${{ !env.NO_CACHE }}
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        if: ${{ !inputs.is-docker }}
      - run: npm install
        if: ${{ inputs.is-docker }}
      - run: ${{ inputs.test-script }}
        timeout-minutes: 60

  set-result-status:
    if: always()
    needs: test
    uses: ./.github/workflows/set-status.yml
    with:
      status: ${{ fromJSON('["success", "failure"]')[needs.test.result != 'success'] }}
    secrets: inherit