name: Test Functional (Remote macOS)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The test commit SHA or ref'
        required: true
        default: 'master'
      merged_sha:
        description: 'The merge commit SHA'
      deploy_run_id:
        description: 'The ID of a deployment workspace run with artifacts'
jobs:
  test:
    uses: ./.github/workflows/test-functional.yml
    with:
      os: 'macos-latest'
      test-script: 'npx gulp test-functional-travis-desktop-osx-run --steps-as-tasks'
