name: Test Functional

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      execution-failed:
        required: true
        type: boolean

jobs:
  after:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Exit with error
        if: ${{ inputs.execution-failed }}
        run: exit 1
      - uses: actions/github-script@v6
        if: failure()
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'failure',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'success',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });