name: Test Functional

on:
  workflow_call:
    inputs:
      test-script:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest
      node-version:
        required: false
        type: number
        default: 16
      max-parallel-jobs:
        required: false
        type: number
        default: 3
      use-public-hostname:
        required: false
        type: number
        default: 0
      timeout:
        required: false
        type: number
        default: 60
env:
  NO_CACHE: ${{ secrets.NO_CACHE }}

jobs:
  test:
    runs-on: ${{ inputs.os }}
    strategy:
      max-parallel: ${{ inputs.max-parallel-jobs }}
      matrix:
        test-group: [1, 2, 3]
    environment: test-functional
    env:
      USE_PUBLIC_HOSTNAME: ${{ inputs.use-public-hostname }}
      TEST_GROUPS_COUNT: 3
      TEST_GROUP_NUMBER: ${{ matrix.test-group }}
    steps:
      - run: echo "inputs.use-public-hostname is ${{ inputs.use-public-hostname }}."
      - run: echo "env.USE_PUBLIC_HOSTNAME is ${{ env.USE_PUBLIC_HOSTNAME }}."
      - uses: actions/github-script@v3
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'pending',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.merged_sha || github.event.inputs.sha}}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - uses: actions/github-script@v3
        with:
          script: |
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

            let artifacts = {};

            for(let i = 0;i<36&&!artifacts.total_count;i++,await delay(5000)) {
              try {
                ({ data: artifacts } = await github.actions.listWorkflowRunArtifacts({
                repo: context.repo.repo,
                owner: context.repo.owner,
                run_id: context.payload.inputs.deploy_run_id
              }));
              }
              catch (e) {
                console.log(e);
              }
            }

            const { data: artifact } = await github.request(artifacts.artifacts.find(artifact=> artifact.name === 'npm').archive_download_url);
            require('fs').writeFileSync(require('path').join(process.env.GITHUB_WORKSPACE, 'package.zip'), Buffer.from(artifact))

      - run: |
          unzip package.zip
          tar --strip-components=1 -xzf testcafe-*.tgz

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        if: ${{ !env.NO_CACHE }}
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: ${{ inputs.test-script }}
        timeout-minutes: ${{ inputs.timeout }}
      - uses: actions/github-script@v3
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'success',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
      - uses: actions/github-script@v3
        if: failure() || cancelled()
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.inputs.sha,
              context: context.workflow,
              state: 'failure',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
